apiVersion: v1
kind: ReplicationController 
metadata:
  name: mynginx-rc
spec:
  replicas: 4
  selector:
    app: mynginx 
        
  template:
    metadata:
      labels:
        app: mynginx       
    
    spec:
      containers:
        - name: myniginx-container
          image: nginx
          ports:
            - containerPort: 8080


           