apiVersion: v1
kind: ReplicationControler 
metadata: 
  name: mylogin-rc
spec:
  replicas: 2
  selector:
    app: mylogin
  
  template:
    metadata:
      labels:
        app: mylogin
    
    spec:
      containers:
      - name: mylogin-container
        image: maha4iac/mymahalogin:1
        ports:
          - continerPort: 8080
